version: "3.7"

services:
  web:
    restart: always
    build:
      context: ./dockerWeb2/
      dockerfile: ../Dockerfile
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"